### ISSUE TITLE
Download doesn't work through proxies

### ISSUE THREAD

**Issue by janlarres** [mhinz/vim-rfc#3]
Hi,

at work all of our traffic goes through a proxy, configured with the `$http_proxy`/`$https_proxy` environment variable. This plugin doesn't seem to support that situation, so I'm getting this:

```
Error detected while processing function rfc#query:
line   33:
Errno::ENETUNREACH: Failed to open TCP connection to www.rfc-editor.org:80 (Network is unreachable - connect(2) for "www.rfc-editor.org" port 80)
```

It would be great if proxy support could be added. Thanks!

**Comment by mhinz** [comment]
Hi,

if I read the [documentation](https://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new) correctly, this small change should be enough.

**Comment by janlarres** [comment]
It is indeed working now, thanks!

**Comment by mhinz** [comment]
Now that was easy!

Thanks for reporting.
