### ISSUE TITLE
Rfc-editor.org now requires https?

### ISSUE THREAD

**Issue by grepsuzette** [mhinz/vim-rfc#6]
On my new computer I don't manage anymore to get vim-rfc work.
The ruby code runs.

`RFC!` will fail to build the cache.
`~/.vim-rfc.yaml` exists but `~/.vim-rfc.xml` file is not here.

Was wondering if maybe it's because now 
https://www.rfc-editor.org/in-notes/rfc-index.xml requires https (this is a different source than in https://github.com/mhinz/vim-rfc/pull/4).

Anyway I can do without for now but thought I would open an issue about this.

**Comment by mhinz** [comment]
Better late than never!

Thanks for letting me know. I wasn't exactly active recently, but I'm working at my comeback. ;]
